version: '3.8'
services:
  nginx:
    build: ./
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/localhost.crt
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/localhost.key
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - travel_note_frontend
      - travel_note_backend
  travel_note_frontend:
    build: 
      context: ../travel_note_frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../travel_note_frontend:/app
      - /app/node_modules
    ports:
      - 5001:5001
    environment: 
      - CHOKIDAR_USEPOLLING=true

  travel_note_backend:
    build: 
      context: ../travel_note_backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../travel_note_backend:/app
      - /app/node_modules
  
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data: