version: '3.8'
services:
  nginx:
    build: ./
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../localhost.crt:/etc/nginx/ssl/localhost.crt
      - ../localhost.key:/etc/nginx/ssl/localhost.key
    ports:
      - 5003:443
    depends_on:
      - travel_note_frontend
      - travel_note_backend
  travel_note_frontend:
    build: 
      context: ../travel_note_frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../travel_note_frontend:/app
      - /app/node_modules
    ports:
      - 5001:5001
    depends_on:
      - travel_note_backend

  travel_note_backend:
    build: 
      context: ../travel_note_backend
      dockerfile: Dockerfile
      target: development
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ../travel_note_backend:/app
      - /app/node_modules
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      timeout: 20s
      retries: 10
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data: