name: TravelNote-Configs-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -T terry998877terry@34.80.219.26 \
          "cd /home/travel_note/travel_note_frontend
          echo 'VITE_APP_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}' > ./.env && \
          cd /home/travel_note/travel_note_backend/config && \
          mkdir -p ./keys && \
          cd /home/travel_note/travel_note_configs && \
          mkdir -p ./config/keys && \
          echo '${{ secrets.JWT_PRIVATE_KEY }}' > ./config/keys/private.key && \
          echo '${{ secrets.JWT_PUBLIC_KEY }}' > ./config/keys/public.key && \
          git pull && \
          sudo docker-compose -f docker-compose.prod.yml up --build -d"
